<html>
<head>
	<style>
		.dot{
  border-style: solid;
  border-width: 5px;
  background-color: yellow;
}
body{
	background-color: black;
}


	</style>
</head>
<body>
	<center>
	<div class="dot">
	<p><a href="adminlogin.php">Users</a><br></p>
	<p><a href="adminnoofchildren.php">Children in orphanage</a><br></p>
	<p><a href="admininsert.php">Insert new children</a><br></p>
	
	<p><a href="adminnewchild.php">Adopted children</a><br></p>
</center>
</div>
</body>
</html>